-- After creating your first Supabase Auth user, run a row like this with the same email.
-- insert into public.staff_members (full_name, initials, email, role)
-- values ('Your Name', 'YN', 'you@example.com', 'admin')
-- on conflict (email) do update set role = excluded.role, is_active = true;
